export default {
  PRIMARY_COLOR: '#EAE9E4',
  SECONDARY_COLOR: '#DFDCCF',
  WHITE_COLOR: '#FFF',
  BLACK_COLOR: '#000',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  BACKGROUND_COLOR_LIGHT: '#f0f6f7',
  CONTAINER_PADDING: 20,
};
